CREATE DATABASE CHESS;

CREATE TABLE PLAYERS (
ID INT,
FIRSTNAME VARCHAR(50)

);

INSERT INTO PLAYERS (ID, FIRSTNAME) VALUES (1, 'SAINI');
INSERT INTO PLAYERS (ID, FIRSTNAME) VALUES (2, 'DEEPANSHU');

SELECT * FROM PLAYERS;
